### ISSUE TITLE
Issues with carriage return on align center

### ISSUE THREAD

**Issue by LilyMihalik** [datadesk/meme#10]
Before user hits return to move the text down:
![image](https://cloud.githubusercontent.com/assets/1634854/10523744/d8316146-7330-11e5-80f1-f79f8a434995.png)

After user hits return to move the text down "undefined" appears in the text
![image](https://cloud.githubusercontent.com/assets/1634854/10523761/ebfd3e66-7330-11e5-9a22-a4740d123f0b.png)

**Comment by palewire** [comment]
Huh.
